// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRSPdlhCXsoyB6yi1lQ4_Zpt_5jJz4LIA',
    appId: '1:785314745418:web:32a95d1b731b085838eab3',
    messagingSenderId: '785314745418',
    projectId: 'mongez-cdfb6',
    authDomain: 'mongez-cdfb6.firebaseapp.com',
    storageBucket: 'mongez-cdfb6.firebasestorage.app',
    measurementId: 'G-HEQXYKCRCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMXacIXe7THuWx2cnt38lEX72YkCzcn50',
    appId: '1:785314745418:android:17447565e5b0dc4738eab3',
    messagingSenderId: '785314745418',
    projectId: 'mongez-cdfb6',
    storageBucket: 'mongez-cdfb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyYrpBcvUTG2ptrwd5_xSHKSDlGlfLWxE',
    appId: '1:785314745418:ios:8d02a3b76a89096438eab3',
    messagingSenderId: '785314745418',
    projectId: 'mongez-cdfb6',
    storageBucket: 'mongez-cdfb6.firebasestorage.app',
    iosBundleId: 'com.example.mongiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyYrpBcvUTG2ptrwd5_xSHKSDlGlfLWxE',
    appId: '1:785314745418:ios:8d02a3b76a89096438eab3',
    messagingSenderId: '785314745418',
    projectId: 'mongez-cdfb6',
    storageBucket: 'mongez-cdfb6.firebasestorage.app',
    iosBundleId: 'com.example.mongiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRSPdlhCXsoyB6yi1lQ4_Zpt_5jJz4LIA',
    appId: '1:785314745418:web:7471ce044ef7e35738eab3',
    messagingSenderId: '785314745418',
    projectId: 'mongez-cdfb6',
    authDomain: 'mongez-cdfb6.firebaseapp.com',
    storageBucket: 'mongez-cdfb6.firebasestorage.app',
    measurementId: 'G-M6ZPNCY5WP',
  );
}
