import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:mongiz/constans.dart';
import 'package:mongiz/core/helper_functions/on_generate_routes.dart';
import 'package:mongiz/features/splash/presentation/view/splash_view.dart';
import 'firebase_options.dart'; // This file is generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const Mongiz());
}

class Mongiz extends StatelessWidget {
  const Mongiz({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,

      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: kScaffoldDarkColor,

        colorScheme: ColorScheme.fromSeed(
          seedColor: kAppPrimaryColor,
          brightness: Brightness.dark,
          primary: kAppPrimaryColor,
        ),

        textTheme: ThemeData.dark().textTheme
            .apply(fontFamily: 'OmarRegular')
            .copyWith(
              titleLarge: ThemeData.dark().textTheme.titleLarge?.copyWith(
                fontFamily: 'OmarBold',
              ),
            ),
      ),

      onGenerateRoute: onGenerateRoutes,
      initialRoute: SplashView.routeName,
    );
  }
}
